### ISSUE TITLE
error: packages/flutter_tools/bin/flutter_tools.dart: does not match index

### ISSUE THREAD

**Issue by kasentom** [skylerpfli/flutter_aop_demo#1]
1.对FlutterSdk打补丁

cd /Users/xxxx/tools/flutter2.2.0/packages/flutter_tools 
git apply --3way /Users/xxxx/Documents/dart_coverage/aop_demo20220126/flutter_aop_demo/aop_flutter_sdk_2.2.0.patch 

error: packages/flutter_tools/bin/flutter_tools.dart: does not match index
error: packages/flutter_tools/lib/src/compile.dart: does not match index

是在这个目录下执行么？

**Comment by skylerpfli** [comment]
在FlutterSdk目录下打git补丁就可以

**Comment by skylerpfli** [comment]
可以检查：

**Comment by skylerpfli** [comment]
可以检查是不是在2.2.0版本，并且是无修改的哈。看提示应该是git合并冲突了
